print("-" * 35)
print('Tugas 1 SISOP Kelas-A')
print('-' * 35)
print('Nama : Amanda Ayu Dewi Lestari')
print('NPM : 21083010008')
print('-' * 35)
print('notes: ')
print('-' * 35)
print('Halo Dunia!')
print('Ini adalah script Bash pertamaku di Linux')
